### ISSUE TITLE
Quick question: Some of the buttons don't work in a iframe

### ISSUE THREAD

**Issue by KUKHUA** [meething/webrtctzn#3]
Hello! I used Deta to host an instance of this, but when I try to frame it most of the buttons do not work. Anyone know how I could fix this, or why it is happening?
Here is my code for context:
`var win = window.open();
var num = Math.floor(Math.random() * 101);
var url = "https://mydetaurl.com/?room=lucky&video&username=anon_" + num;
var iframe = win.document.createElement('iframe');
iframe.style.width = "100vw";
iframe.style.height = "100vh";
iframe.style.border = "none";
iframe.style.position = "absolute";
iframe.style.top = "0";
iframe.style.left = "0";
iframe.src = url;
win.document.body.appendChild(iframe);`

**Comment by KUKHUA** [comment]
Oh wait... Is it cuz: ` allowusermedia 
  allow="microphone; camera; encrypted-media;">` ain't there?

**Comment by lmangani** [comment]
If you're operating within an iframe, yes that would be a blocker.

**Comment by lmangani** [comment]
Awesome! let us know how it goes

**Comment by KUKHUA** [comment]
Okay soo... it does not seem to work? 
I have two devices joining with the url:
`var num = Math.floor(Math.random() * 101);
var url = "https://mydetaurl.com/?room=lucky&video&username=anon_" + num;``
The other device is not there?
Is there some extra step I'm missing to make it work?

**Comment by lmangani** [comment]
Hard to tell since the beauty of p2p is everything remains in your browser. Look at the console for hints as of what might be going wrong. Does the public demo work for you?

**Comment by KUKHUA** [comment]
I'm not sure about this; but I think it has to do with the hosting or cloudflare stuff.
The devices I'm trying to use this on are pretty heavily restricted, so I tried them with my phones and they did not work either. (I tried the public demo on my phones aswell)
My domain is ch.basicfan.eu.org btw.

**Comment by lmangani** [comment]
I pushed an update to use the latest trystero version. Could you give it a try?

**Comment by KUKHUA** [comment]
Okay... Um I don't know how to host this...
The one in Deta was like a template, and for some reason they do not have a feature to edit that.
So, I have to make my own thing in Deta to host the new version. What commands do I use to host it & install the packages?
I can't figure it out...

**Comment by lmangani** [comment]
There's nothing to install, its all served by a static page. Clone this repository and copy it in your webfolder.
The deta and glitch versions are basically just this repository with very few modifications.

**Comment by KUKHUA** [comment]
Um… It doesn't look right? Did I do something wrong? https://dyiyg-1-i1738239.deta.app/?room=cy
Also error:
[dyiyg-1-i1738239.deta.app-1684439222995.log](https://github.com/meething/webrtctzn/files/11511138/dyiyg-1-i1738239.deta.app-1684439222995.log)
