### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by KUKHUA** [meething/webrtctzn#4]
Hello!
Is there any way you could make a docker that setup this, and hosts the p2p (stun I think) servers?

**Comment by lmangani** [comment]
Hello @KUKHUA the beauty about this project is the fact it doesn't require a dedicated server or a docker container.
WebRTCtzn just needs the static page served and the rest is powered by the browser and uses p2p and public torrent servers to find and connect with other users.  Host it on any free web service with a domain such as glitch, github, pages, etc. 

Hope this helps!

**Comment by lmangani** [comment]
You don't have to host the torrent servers. The is designed for public usage and the underlying library uses the same DHT servers used by millions of other applications to share files, videos, etc, (as well as other methods) to resolve users  in the same server/room and connect them through p2p websockets.

**Comment by KUKHUA** [comment]
I wish to host them.

**Comment by lmangani** [comment]
@KUKHUA we can't help you with that, but webrtctzn should most likely be able to use any DHT you configure it for. Good Luck!
